
#ifndef __GD_FIREBASE_CONFIG_H__
#define __GD_FIREBASE_CONFIG_H__

#include "gd_macros.h"

#define GD_FIREBASE_DEBUG		true

#define GD_FIREBASE_ADMOB		1
#define GD_FIREBASE_ANALYTICS		1
#define GD_FIREBASE_AUTHENTICATION	1
#define GD_FIREBASE_NOTIFICATION	1
#define GD_FIREBASE_INVITES		1
#define GD_FIREBASE_REMOTECONFIG	1
#define GD_FIREBASE_STORAGE		1

#if GD_FIREBASE_ADMOB
// The AdMob app IDs.
#endif

#endif // __GD_FIREBASE_CONFIG_H__
